---
- hosts: target
  roles:
    - buildtools
    - redis
    - supervisor
    - iptables
    - newrelic

- hosts: target-dbserver
  roles:
    - rethinkdb

- hosts: target-webserver
  roles:
    - nginx
    - celery
    - uwsgi
